### ISSUE TITLE
Produce initial and final photon spectra and add it to README

### ISSUE THREAD

**Issue by ignotur** [ignotur/magnetar_spectrum#7]

**Comment by biaozhang123** [comment]
how to make photho.cpp run?

**Comment by biaozhang123** [comment]
Excuse me, how to run the program and get the spectrum of the magnetar correctly

**Comment by ignotur** [comment]
Sorry for the delayed reply, for some reasons I missed all messages. 
The code can be run now as ./magpies.out

The initial and final spectra are produced now.
